### ISSUE TITLE
How can I open diff view when I use my customized template?

### ISSUE THREAD

**Issue by camtl107** [gitbito/bitoai#134]
when I use my customized template and it rewrites the code ,I wish the diff view can open automatically like Security Check template

**Comment by bitoandy** [comment]
Hi @camtl107 ,

We have added this to our product roadmap. Will keep this open till the support is available.

**Comment by nisha-bito** [comment]
hi @camtl107 ,

Bito latest version 1.1.9 has support for this. Please install the new Bito 1.1.9 and let us know if this fix your problem.

Thanks,
Nisha

**Comment by camtl107** [comment]
> hi @camtl107 ,
> 
> Bito latest version 1.1.9 has support for this. Please install the new Bito 1.1.9 and let us know if this fix your problem.
> 
> Thanks, Nisha

I install the Bito 1.2.1,my problem is not solved。My comment template looks like this:

The comment should be in the following format. 
/** 
 * @brief  <what the function does> 
 *  
 * @param  <the meanings of all parameters> 
 * @return  <the meaning of return value> 
 */ 
 comment code ,and rewrite the code if possible.
 
but it can not open diff view after generate comment.
and I also have a problem:the he code auto-completion function does not take effect after I enable it。such as:
![image](https://github.com/gitbito/bitoai/assets/136044336/0136b3d0-41e2-4b12-b538-29ba21e66391)
It stays in this state and produces no code. I can make sure my Internet is working.

**Comment by nisha-bito** [comment]
hi @camtl107,

Thanks for reporting. 
For issue with 1.1.9 version of JetBrains, where diff view is not working, we have a open bug where Diff view is not working when a complete file is selected. IF you can select code snippet from file for now. The fix for the same will be avaialable in the next release which will be released next week. 

Please let us know if you are using JetBrains or VS code? 

Code completion is currently only available in VS code. To use Code completion, please enable it. https://docs.bito.ai/feature-guides/ai-code-completions/enable-disable-settings

please go through more info and a video on how to use the code completion. https://docs.bito.ai/feature-guides/ai-code-completions

Thanks,
Nisha

**Comment by camtl107** [comment]
> hi @camtl107,
> 
> Thanks for reporting. For issue with 1.1.9 version of JetBrains, where diff view is not working, we have a open bug where Diff view is not working when a complete file is selected. IF you can select code snippet from file for now. The fix for the same will be avaialable in the next release which will be released next week.
> 
> Please let us know if you are using JetBrains or VS code?
> 
> Code completion is currently only available in VS code. To use Code completion, please enable it. https://docs.bito.ai/feature-guides/ai-code-completions/enable-disable-settings
> 
> please go through more info and a video on how to use the code completion. https://docs.bito.ai/feature-guides/ai-code-completions
> 
> Thanks, Nisha

I use VS code

**Comment by nisha-bito** [comment]
hi @camtl107 ,

Please upgrade to latest Bito version 1.2.4 and validate of the fix is working for you. 

Thanks,
Nisha
