### ISSUE TITLE
一个扩展使用问题 | An extension usage issue

### ISSUE THREAD

**Issue by AQLIFE** [gitbito/bitoai#17]
扩展视图左上角显示的语言是否影响ai的接受和输出？我不确定这是否影响ai的表达，如果它不影响AI的表达，那么这个扩展视图左上角的编程语言显示是否可以去掉？因为我没有发现它有什么隐藏特性，也无法修改。它甚至不能标识当前工作区的主要编程语言，当然这个功能，也可能尚未创建？亦或者是我没有掌握正确的使用方法？这是一个扩展使用问题，我希望可以得到回复，感谢

Does the language displayed in the upper left corner of the extended view affect the acceptance and output of AI? I'm not sure if this affects the expression of AI, and if it doesn't affect the expression of AI, then the programming language display in the upper left corner of this extended view can be removed? Because I didn't find any hidden features in it, and I can't modify it. It doesn't even identify the primary programming language for the current workspace, and of course this feature may not have been created yet? Or maybe I didn't know how to use it correctly? This is an extension usage issue and I hope to get a reply, thanks

**Comment by AQLIFE** [comment]
我使用的是vs code的bito扩展，这是否在其他IDE中也有这种表现？

I'm using the bito extension for vs code, does this behave this way in other IDEs?

**Comment by bitoandy** [comment]
Hi @AQLIFE ,

Currently we support VS code and JetBrains IDE. Bito extension behaves the same way in both the IDEs.
We currently do not use the primary language of the workspace as users might want to generate code in other languages other than the primary language. We are working on supporting additional settings, where users can set default language (code generation and/or response). 

Also can you provide a screen shot of the screen, so that we can get a better idea about "language displayed in the upper left corner of the extended view". This will help us to understand better and get back to you on any changes we can do within the extension.

**Comment by AQLIFE** [comment]
@bitoandy ok,我可以提供这个截图，以弥补我描述的不足，

**Comment by AQLIFE** [comment]
在这里的语言是指 具有P 字母的哪个图标

The language here refers to which icon has the letter 'P'

**Comment by monicfenga** [comment]
那个“P”是你的workspaces的首字母
在登录的时候让你选择workspaces的时候就能看到
在主界面里，把鼠标放在字母上面，能看到workspaces的名字

**Comment by AQLIFE** [comment]
> 那个“P”是你的workspaces的首字母
> 在登录的时候让你选择workspaces的时候就能看到
> 在主界面里，把鼠标放在字母上面，能看到workspaces的名字

也就是工作区的名字嘛？不具备任何意义?

**Comment by monicfenga** [comment]
> 也就是工作区的名字嘛？不具备任何意义?

对 😂

**Comment by AQLIFE** [comment]
> 那个“P”是你的workspaces的首字母
> 在登录的时候让你选择workspaces的时候就能看到
> 在主界面里，把鼠标放在字母上面，能看到workspaces的名字

好吧，我明白这个的用途了，我会关闭这个问题

**Comment by bitoandy** [comment]
Thanks @monicfenga and @AQLIFE
