### ISSUE TITLE
Does bitoai support VsCodium?

### ISSUE THREAD

**Issue by stefaneidelloth** [gitbito/bitoai#31]
I did not find the extension "Bito" for VSCodium 1.76.2 but only "Bito-vscode-staging".
That extension does not seem to have the tab "Bito AI".

![image](https://user-images.githubusercontent.com/12675339/230167762-05e91b1c-0bbc-4a9e-960b-274aadac9bd0.png)

![image](https://user-images.githubusercontent.com/12675339/230167814-160af8dd-22e9-4838-87b9-f73824dfc07f.png)

**Comment by bitoandy** [comment]
We currently do not officially support VsCodium, that said since its the open source version of Vs Code without telemetry, if you want to run Bito, you can download the extension from VS code marketplace by selecting "Version History" tab next to overview in the extension page for [Bito](https://marketplace.visualstudio.com/items?itemName=Bito.Bito).
 
Once the extension is downloaded (will be file with **vsix** extension), go to the extensions in VsCodium and drag and drop the downloaded vsix file these, this should install Bito extension. 

The direct link to download version 1.0.133 is https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Bito/vsextensions/Bito/1.0.133/vspackage

**Comment by bitoandy** [comment]
New version 1.0.134 is available now at: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Bito/vsextensions/Bito/1.0.134/vspackage
