### ISSUE TITLE
In VS Code, the Bito feedback field and the input field below it, keep failing to copy and paste.

### ISSUE THREAD

**Issue by battleon** [gitbito/bitoai#5]
as the title suggests

**Comment by bitomukesh** [comment]
thanks for reporting this. we are investing it.

**Comment by bitoandy** [comment]
Hi @battleon,

We have added fixes for these in version 1.0.132 please update and let us know if you face any issues

**Comment by nisha-bito** [comment]
hi @battleon ,

VS code has an existing/known issue with the Copy/Paste which appears on right click. This issue is present for all VS Code plugins which uses web view.

Issue Reported on GitHub: 
https://github.com/microsoft/vscode/issues/141080

VS Code Release Updates: https://code.visualstudio.com/updates/v1_57#_context-menus-for-webviews

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @battleon ,

I hope explanation in above comment clarifies the restriction which comes with VS code plugin development tool. 
This ticket will be closed soon, you can always re-open this ticket or create a new ticket if you face any further issues. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @battleon ,

Closing this ticket, however you can always re-open the ticket or create a new ticket if you face any further issue.

Thanks,
Nisha
