### ISSUE TITLE
Copy/Paste issues

### ISSUE THREAD

**Issue by Etienne1232** [gitbito/bitoai#68]
Sometimes, Bito extension in VSCode will not let me copy or paste words into the prompt box. I also sometimes have problems copying data from the prompts generated by Bito. Thanks :)

**Comment by bitoandy** [comment]
@Etienne1232 , which version of Bito plugin/extension are you using?

**Comment by nisha-bito** [comment]
hi @Etienne1232 ,

VS code has an existing/known issue with the Copy/Paste which appears on right click. This issue is present for all VS Code plugins which uses web view. 

**Issue Reported on GitHub:** 
[Context-Menu COPY is not working in vscode webview, BUT ctrl+c is working fine · Issue #141080 · microsoft/vscode](https://github.com/microsoft/vscode/issues/141080)

**VS Code Release Updates**: https://code.visualstudio.com/updates/v1_57#_context-menus-for-webviews

**Comment by Etienne1232** [comment]
My problem is both with CTRL+C and Copy. Neither is working. But since it is a VSCode issue, that's fine. Thank you very much
