### ISSUE TITLE
Crazy huge font size makes plugin unusable.

### ISSUE THREAD

**Issue by byte4ever** [gitbito/bitoai#79]
Hi, currently using the last version of goland, and trying to use bito but font size is way to big to make the plugin usable.

Plugin seems very promissing btw!

![Screenshot from 2023-06-07 01-29-31](https://github.com/gitbito/bitoai/assets/9654728/f036f2e0-deb8-4193-9c51-a1f9f9efd098)

**Comment by bitoandy** [comment]
@byte4ever, can you provide the version of Bito plugin you are using

**Comment by KumarVariable** [comment]
Hi @byte4ever ,

Thanks for reaching out and reporting the issue faced by you.

Based on the screenshot shared by you, can you please share the screenshot of 'Settings' for the GoLand editor too?
This will help us to confirm as there are no custom font settings for the BITO plugin enabled in the GoLand editor

Sample screenshot as below:

Bito Plugin: v1.0.138
GoLand Build: GO-231.9011.34 

![image](https://github.com/gitbito/bitoai/assets/79558369/fc89e45c-8bf9-42fa-9909-d4757ebbc616)

FYI,
The size of fonts in the BITO plugin can be updated  by providing Font type and Font Size through File -> Settings -> Appearance & Behavior -> Appearance -> Select (Use Custom Font)

Please do reach out to us for any assistance.

**Comment by byte4ever** [comment]
Hi here is my current font setting.

![Screenshot from 2023-06-12 13-13-42](https://github.com/gitbito/bitoai/assets/9654728/054cbb62-e6e9-4e01-92f8-594a9f4b37c9)

**Comment by KumarVariable** [comment]
HI @byte4ever ,

Thanks for responding and glad that you brought your concern to our attention.

Just for heads up, To decrease the font size in BITO UI you need to de-select the checkbox 'Use custom Font' or, decrease the font size and re-load your GoLand Editor

Since it's not possible for you to decrease the font size because of your work, I am sorry, that at present there is no other option available to decrease the font size in BITO, and we will consider this change in our upcoming releases.

Why BITO UI panel is affected by this setting?

Earlier we received suggestions from many of our users that they want the styling of text responses in BITO as per their Editor's font settings and hence the font type and font size in BITO UI are in sync with the end user's editor settings.

Please do connect with us if you need further assistance

**Comment by nisha-bito** [comment]
hi @byte4ever ,

This ticket will be closed now. Please feel free to create new ticket for any further issues at your end. 

Thanks,
Nisha
