### ISSUE TITLE
Bito window can not show correctly.

### ISSUE THREAD

**Issue by Happy-ArthurYang** [gitbito/bitoai#88]
My Ide version is 
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to Syngenta / Jie Yang
Subscription is active until October 10, 2023.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 4
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    org.intellij.plugins.hcl (231.8109.91)
    co.bito.bito-intellij (1.0.138)
    zielu.gittoolbox (500.0.10+213)
    aws.toolkit (1.69-231)

Kotlin: 231-1.8.21-IJ9011.34
Bito version
1.0.138
when clicked the Bito icon on the side bar only shows me a blank working area , but not the interactive UI.
![image](https://github.com/gitbito/bitoai/assets/113080404/5ec5082b-472d-4667-8747-741b1eea7a22)
also attach intelliJ start log.
[idea.log](https://github.com/gitbito/bitoai/files/11766238/idea.log)

**Comment by bitoandy** [comment]
Thanks @Happy-ArthurYang  for the details, we will keep you posted on the issue and fixes.

**Comment by nisha-bito** [comment]
hi @Happy-ArthurYang ,

From the logs i see that you have JCEF-sandbox is enabled.

The sandbox is a security mechanism used to isolate untrusted code from the rest of the system to prevent it from causing damage. 

Enabling the JCEF sandbox in IntelliJ IDEA can prevent plugins that use the JCEF browser from loading or displaying properly. This is because the sandbox is a security mechanism that isolates untrusted code from the rest of the system, and this can cause issues with plugins that require access to certain system resources or APIs. If you're experiencing issues with a JCEF-based plugin in IntelliJ IDEA, you may need to disable the sandbox to allow the plugin to function properly. However, disabling the sandbox can potentially introduce security risks[ Specially if you have enabled it for some reason] , so it's important to weigh the benefits and drawbacks before making any changes.

Please note: Bito uses JCEF browser. 

Thanks,
Nisha

**Comment by Happy-ArthurYang** [comment]
I think there is no special reason JCEF sandbox was enabled, could you tell me how to disable it, thank you?

**Comment by nisha-bito** [comment]
please refer this - https://share.bito.co/static/share?aid=b5f10a1a-c525-410f-9333-608b607a6093 to make the changes

**Comment by Happy-ArthurYang** [comment]
Still the same,
![image](https://github.com/gitbito/bitoai/assets/113080404/607514dd-3a32-433f-9f43-562744576c9e)
![image](https://github.com/gitbito/bitoai/assets/113080404/e167e489-82bc-4b4b-9967-e8317416e33b)
[idea.log](https://github.com/gitbito/bitoai/files/11769251/idea.log)

**Comment by nisha-bito** [comment]
in the latest log also, i see the Sandbox is enabled. Can you try to restarted the Intellj once ?
![image](https://github.com/gitbito/bitoai/assets/123052606/d41f95c5-9aba-4c0c-82e6-f49ae6d59b65)


Alternative, please try below steps -
Open IntelliJ IDEA and go to "Help" -> "Edit Custom Properties". 
2. Add the following line to the custom properties file:
-Djcef.sandbox=false
3. Save the file and close it. 
4. Restart IntelliJ IDEA for the changes to take effect.

**Comment by Happy-ArthurYang** [comment]
Yes this works, thanks a lot.
